<?php

function framework_uploader_menu() {
    $items = array();
    
    $items['code-uploader'] = array(
        'title' => t('Upload a file'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('framework_uploader_code_form'),
        'access callback' => TRUE
    );

    return $items;
}

function framework_uploader_code_form($form, &$form_state) {
    $form = array();
    
    $form['code-upload-file'] = array(
        '#title' => t('Upload codes'),
        '#type' => 'file'
    );

    $form['submit-file'] = array(
        '#type' => 'submit',
        '#value' => t('Upload')
    );
    
    $form['#validate'] = array(
        'framework_uploader_code_validate_fileupload',
        'framework_uploader_code_form_validate',
      ) ;
      return $form ;
    }

function framework_uploader_code_validate_fileupload(&$form, &$form_state) {
    $validators = array(
        'file_validate_extensions' => array('csv')
    ); 

    if ($file = file_save_upload('code-upload-file', $validators, "public://", FILE_EXISTS_REPLACE)) {
        $form_state['values']['code-upload-file'] = $file->destination;
    } else {
        form_set_error('code-upload-file', t('Unavle to copy upload file to !dest', array('!dest' => $destination)));
    }
}

function framework_uploader_code_form_validate($form, &$form_state) {
    
    if (isset($form_state['values']['code-upload-file'])) {
        if ($handle = fopen($form_state['values']['code-upload-file'], 'r')) {
            $line_count = 1;
            $first = true; 
            // $iteration = 0; // Keep track of the passes 
            /** For now, let's try not to prematurely optimize 
             * when you're not even sure which should be faster: 
             * logic check for iteration just to validate the headers once 
             *  (logic check, array comparison, 
             *   increment index for logic check,
             *   then looping back through having to evaluate the conditional then parsing the file contents)
             * OR 
             * 
             * calling fgetscsv twice
             *  once to check the headers
             *  then one more time with a while loop to parse the file's contents
             *  
             */
            if ($line = fgetcsv($handle, 4096)) {
                // First iteration of while loop should be the file headers
                $headers = array('First Name', 'Last Name', 'Secret Identity');
                $line === $header ? '' : form_set_errors('Incorrect headers');
            }

            while($line = fgetscsv($handle, 4096)) {
                

            }
        }
    }
    
}
function framework_uploader_code_form_submit($form, &$form_state) {
    dpm($form_state);
    
}