<?php
/**
 * Implements hook_menu()
 * Note - D7 uses hook_menu to register/associate a path with a module
 * D8 has a different routing system that at a glance, reminds me of React Router/React's way of registering components
 * 
 */

module_load_include('inc.php', 'form', 'framework_add_parent_form');

define('DRUPAL_GET_FORM', 'drupal_get_form', false); // I'm too lazy to type the string

function framework_add_parent_menu() {
    // $items = convention
    // The whole point of hook_menu() is to return an array of things
    $items = array();
    
    $items['/add/parent'] = array(
        'access callback' => TRUE,
        'page callback' => DRUPAL_GET_FORM,
        'page arguments' => 'framework_add_parent_form',
        'file' => 'framework_add_parent.form.inc.php'
    );

    return $items;
    
}

?>

